title: Atlas of Basketball
email: josh@kfcartography.com
description: >
  A blog to explore various ways to represent basketball, specifically NBA,
  data. Developed by Josh Ryan.
baseurl: "/atlas-of-basketball"
url: "https://kingfisher13.github.io"
twitter_username: karenkingfisher
github_username:  kingfisher13

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
